global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus_service"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "nodejs_service"
    static_configs:
      - targets: ["host.docker.internal:8080"]
