version: "3.4"
name: aa2
services:
  db:
    image: mariadb:11.3.2
    container_name: aa2-db-dev
    environment:
      MYSQL_PORT: 3306,
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "alvaro"
      MYSQL_PASSWORD: "alvaro"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
